### ISSUE TITLE
Update Repo README

### ISSUE THREAD

**Issue by mike-myers-tob** [trailofbits/sinter#13]
### Why
As a security engineer that uses GitHub, I want to be able to find important information about the purpose, uses, and configuration of Sinter so that I can decide if it is a good match for my organization's device process control.

### Acceptance Criteria
- README includes
    - explanation of who this tool is for
    - features
    - anti-features
    - key differences from santa
    - quick-start guide
    - Include instructions on building and signing for deployment

### Tasks
- [x] explanation of who this tool is for
- [x] features
- [x] anti-features
- [x] key differences from santa
- [x] quick-start guide
- [x] Include instructions on building and signing for deployment

### Dev Notes
See https://github.com/roshanlam/ReadMeTemplate
